# DP 动态规划

## 上台阶问题

In [23]:
# max=10
def dp(n):
    results=[0]*11
    for j in range(10):
        i=10-j
        #print('>>i=', i, results)
        if i>= (10-1):
            results[i]=1
        else:
            results[i]=results[i+1]+results[i+2]
        if i==n:
            break;
    return results[n]
# test
for j in range(10):
    i=10-j
    print('i=%d, steps=%d' % (i, dp(i) ) )

i=10, steps=1
i=9, steps=1
i=8, steps=2
i=7, steps=3
i=6, steps=5
i=5, steps=8
i=4, steps=13
i=3, steps=21
i=2, steps=34
i=1, steps=55


## 斐波那契数列

In [28]:
def fib(n):
    results=list(range(n+1))
    for i in range( n+1 ):
        if i<2:
            results[i]=i
        else:
            results[i] = results[i-1] + results[i-2] 
    return results[-1]
# test
for i in range(20):
    print(fib(i))

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181


## 走迷宫问题

In [74]:
# m行 n列
def walk(m,n):
    #results=[[0]*n]*m
    results=[[0 for i in range(n)] for j in range(m)]
    return results
# test
a=walk(7,3)

print(a)
a[1][2]=512
a

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


[[0, 0, 0], [0, 0, 512], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [76]:
def walk(m,n):
    results=[[1 for i in range(n)] for j in range(m)] #[[1]*n]*m
    
    for i in range(1,m):
        for j in range(1,n):
            if results[i][j] == 1: #如果是初始值，则更新
                results[i][j]=results[i-1][j] + results[i][j-1]
            print('>> i=%d, j=%d' %(i,j),results)
    return results[-1][-1]
# test
walk(7,3)

>> i=1, j=1 [[1, 1, 1], [1, 2, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
>> i=1, j=2 [[1, 1, 1], [1, 2, 3], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
>> i=2, j=1 [[1, 1, 1], [1, 2, 3], [1, 3, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
>> i=2, j=2 [[1, 1, 1], [1, 2, 3], [1, 3, 6], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
>> i=3, j=1 [[1, 1, 1], [1, 2, 3], [1, 3, 6], [1, 4, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
>> i=3, j=2 [[1, 1, 1], [1, 2, 3], [1, 3, 6], [1, 4, 10], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
>> i=4, j=1 [[1, 1, 1], [1, 2, 3], [1, 3, 6], [1, 4, 10], [1, 5, 1], [1, 1, 1], [1, 1, 1]]
>> i=4, j=2 [[1, 1, 1], [1, 2, 3], [1, 3, 6], [1, 4, 10], [1, 5, 15], [1, 1, 1], [1, 1, 1]]
>> i=5, j=1 [[1, 1, 1], [1, 2, 3], [1, 3, 6], [1, 4, 10], [1, 5, 15], [1, 6, 1], [1, 1, 1]]
>> i=5, j=2 [[1, 1, 1], [1, 2, 3], [1, 3, 6], [1, 4, 10], [1, 5, 15], [1, 6, 21], [1, 1, 1]]
>> i=6, j=1 [[1, 1, 1], [1, 2, 3], [1, 3, 6], [1, 4, 10], [1, 5, 15], [1, 6, 21], [1, 7, 1]

28

In [45]:
import numpy as np
def walk(m,n):
    results=np.ones( (m,n) )
    
    for i in range(1,m):
        for j in range(1,n):
            if results[i][j]==1: #如果是初始值，则更新
                results[i][j]=results[i-1][j] + results[i][j-1]
            print('>> i=%d, j=%d \n' %(i,j),results)
    return results[-1][-1]
# test
walk(7,3)

>> i=1, j=1 
 [[1. 1. 1.]
 [1. 2. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
>> i=1, j=2 
 [[1. 1. 1.]
 [1. 2. 3.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
>> i=2, j=1 
 [[1. 1. 1.]
 [1. 2. 3.]
 [1. 3. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
>> i=2, j=2 
 [[1. 1. 1.]
 [1. 2. 3.]
 [1. 3. 6.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
>> i=3, j=1 
 [[1. 1. 1.]
 [1. 2. 3.]
 [1. 3. 6.]
 [1. 4. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
>> i=3, j=2 
 [[ 1.  1.  1.]
 [ 1.  2.  3.]
 [ 1.  3.  6.]
 [ 1.  4. 10.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
>> i=4, j=1 
 [[ 1.  1.  1.]
 [ 1.  2.  3.]
 [ 1.  3.  6.]
 [ 1.  4. 10.]
 [ 1.  5.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
>> i=4, j=2 
 [[ 1.  1.  1.]
 [ 1.  2.  3.]
 [ 1.  3.  6.]
 [ 1.  4. 10.]
 [ 1.  5. 15.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
>> i=5, j=1 
 [[ 1.  1.  1.]
 [ 1.  2.  3.]
 [ 1.  3.  6.]
 [ 1.  4. 10.]
 [ 1.  5. 15.]
 [ 1.  6.  1.]
 [ 1.  1.  1.]]
>> i=5, j=2 
 [[ 1.  1.  

28.0